version: 2.1
executors:
  default:
    docker:
      - image: cimg/php:7.2.32
workflows:
  build-test:
    jobs:
      - build
      - test:
          requires:
            - build
jobs:
  build:
    executor: default
    steps:
      - setup-environment
      - install-magento
      - copy-repo
      - run: ls -R
commands:
  setup-environment:
    steps:
      - run:
          name: install magento dependencies
          command: sudo apt-get update && sudo apt-get install php7.2-bcmath && sudo apt-get install php7.2-intl && sudo apt-get install php7.2-soap
  install-magento:
    steps:
      - run:
          name: download and install Magento 2
          command: git clone -b 2.3 https://github.com/magento/magento2 ./ && composer install magento2 && mkdir -p magento2/app/code/Pixlee/Pixlee
  checkout-repo:
    steps:
      - run:
          name: checkout extension repo to proper directory
          command: rsync -av --progress . magento2/app/code/Pixlee/Pixlee/ --exclude magento2

