<?php
/* @var \Pixlee\Pixlee\Block\Adminhtml\System\Config\Export $block */
?>

<script>
require(['prototype'], function () {

    window.exportToPixlee = function(url){
      var $button = $('pixlee_export_button')
      if($button.hasClassName('disabled')) {
        return;
      }

      $button.addClassName('disabled');
      new Ajax.Request('<?= /* @noEscape */ $block->getAjaxExportUrl() ?>', {
        // method:    'get',
        onSuccess: function(response){
          if (response.responseText){
            var json = response.responseText.evalJSON(true);

            if(json.pixlee_remaining_text) {
              $('pixlee_remaining').update(json.pixlee_remaining_text);
            }
            if(json.action === 'continue' && json.url) {
              $('pixlee_export_button').removeClassName('disabled');
              exportToPixlee(json.url);
            }
          }
        }
      });
    }
  });
</script>

<?= $block->getButtonHtml() ?>
<p class="note"><span id="pixlee_remaining"><?= /* @noEscape */ $block->getPixleeRemainingText(); ?></span></p>
