<?php
/**
 * Category view template
 *
 * @var $block \Magento\Catalog\Block\Category\View
 */
?>
<?php
$helper = $this->helper('Pixlee\Pixlee\Helper\Data');
$nativeCategoryId = $block->getCurrentCategory()->getId();
$websiteId = $helper->getWebsiteId();
$helper->initializePixleeAPI($websiteId);
?>
<?php if ($helper->isActive() && $helper->getCDPWidgetId() != "") : ?>
    <div id="pixlee_container"></div>
    <div id="pixlee_widget_master_container"></div>
    <script id="pixlee_script">

    window.PixleeAsyncInit = function() {
        Pixlee.init({
            apiKey: '<?= /* @noEscape */ $helper->getApiKey(); ?>'
        });
        Pixlee.addCategoryWidget({
            widgetId: <?= /* @noEscape */ $helper->getCDPWidgetId(); ?>,
            nativeCategoryId: <?= /* @noEscape */ $nativeCategoryId; ?>,
            ecomm_platform: 'magento'
        });
    };
    </script>
    <script src="https://assets.pixlee.com/assets/pixlee_widget_1_0_0.js"></script>
<?php endif; ?>