<?php
/**
 * Copyright © Pixlee TurnTo, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/* @var \Magento\Catalog\Block\Category\View $block */
/* @var \Pixlee\Pixlee\ViewModel\ProductWidget $viewModel */
$viewModel = $block->getViewModel();
$nativeCategoryId = $block->getCurrentCategory()->getId();
?>
<?php if ($viewModel->isActive() && !empty($viewModel->getCDPWidgetId())) : ?>
    <div id="pixlee_container"></div>
    <div id="pixlee_widget_master_container"></div>

    <script type="text/x-magento-init">
        {
            "*": {
                "Pixlee_Pixlee/js/cdp-widget":{
                    "apiKey": "<?= $block->escapeJs($viewModel->getApiKey()) ?>",
                    "widgetId": <?= $block->escapeJs($viewModel->getCDPWidgetId()) ?>,
                    "nativeCategoryId": <?= $block->escapeJs($nativeCategoryId) ?>
                }
            }
        }
    </script>
<?php endif; ?>
