<?php
$helper = $block->getDataHelper();
$websiteId = $helper->getWebsiteId();
$helper->initializePixleeAPI($websiteId);
?>

<?php if ($helper->isActive()) : ?>
    <script type="text/javascript">
        require(["https://assets.pixlee.com/assets/pixlee_events.js"], function() {
            window.pixlee_analytics = new Pixlee_Analytics('<?= /* @noEscape */ $helper->getApiKey(); ?>');
        });
    </script>
<?php endif; ?>
