<?php /* @var $block \Pixlee\Pixlee\Block\Gallery */?>
<?php
$helper = $this->helper('Pixlee\Pixlee\Helper\Data');
$websiteId = $helper->getWebsiteId();
$helper->initializePixleeAPI($websiteId);
$_product = $block->getProduct();
?>
<?php if ($helper->isActive() && $helper->getPDPWidgetId() != "") : ?>
    <div id="pixlee_container"></div>
    <div id="pixlee_widget_master_container"></div>
    <script id="pixlee_script" type="text/javascript">
        require(['https://assets.pixlee.com/assets/pixlee_widget_1_0_0.js'], function (pixlee) {
            Pixlee.init({apiKey: '<?= /* @noEscape */ $helper->getApiKey(); ?>'});
            Pixlee.addProductWidget({
                widgetId: <?= /* @noEscape */ $helper->getPDPWidgetId(); ?>,
                skuId: '<?= /* @noEscape */ $_product->getSku(); ?>',
                accountId:<?= /* @noEscape */ $helper->getAccountId(); ?>
            });
            Pixlee.resizeWidget();
        });
    </script>
<?php endif; ?>