<?php
/**
 * Copyright © Pixlee TurnTo, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/* @var \Magento\Catalog\Block\Product\View $block */
/* @var \Pixlee\Pixlee\ViewModel\ProductWidget $viewModel */
$viewModel = $block->getViewModel();
$product = $block->getProduct();
?>
<?php if ($viewModel->isActive() && !empty($viewModel->getPDPWidgetId())) : ?>
    <div id="pixlee_container"></div>
    <div id="pixlee_widget_master_container"></div>

    <script type="text/x-magento-init">
        {
            "*": {
                "Pixlee_Pixlee/js/product-widget":{
                    "apiKey": "<?= $block->escapeJs($viewModel->getApiKey()) ?>",
                    "widgetId": <?= $block->escapeJs($viewModel->getPDPWidgetId()) ?>,
                    "skuId": "<?= $block->escapeJs($product->getSku()) ?>",
                    "accountId": <?= $block->escapeJs($viewModel->getAccountId()) ?>
                }
            }
        }
    </script>
<?php endif; ?>
