<?php
/**
 * Copyright © Pixlee TurnTo, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/* @var \Magento\Catalog\Block\Product\View $block */
/* @var \Pixlee\Pixlee\ViewModel\ProductWidget $viewModel */
$viewModel = $block->getViewModel();
$product = $block->getProduct();
?>
<?php if ($viewModel->isActive() && !empty($viewModel->getPDPWidgetId())) : ?>
    <div id="pixlee_container"></div>
    <div id="pixlee_widget_master_container"></div>
    <script id="pixlee_script" type="text/javascript">
        require(['https://assets.pxlecdn.com/assets/pixlee_widget_1_0_0.js'], function (pixlee) {
            Pixlee.init({apiKey: '<?= /* @noEscape */ $viewModel->getApiKey(); ?>'});
            Pixlee.addProductWidget({
                widgetId: <?= /* @noEscape */ $viewModel->getPDPWidgetId(); ?>,
                skuId: '<?= /* @noEscape */ $product->getSku(); ?>',
                accountId:<?= /* @noEscape */ $viewModel->getAccountId(); ?>
            });
            Pixlee.resizeWidget();
        });
    </script>
<?php endif; ?>
